use crate::error::{DownloadError, DownloadResult};
use magekit_shared::{
    ChannelInfo, ChannelVideoEntry, DownloadOptions, PlatformCookie, TaskId, VideoFormat, VideoInfo,
};
use serde::Deserialize;
use std::io::Write;
use std::path::PathBuf;
use std::process::Stdio;
use tokio::process::{Child, Command};
use tokio::sync::mpsc;
use tokio::time::Duration;

/// 视频下载器
#[derive(Clone)]
pub struct VideoDownloader {
    yt_dlp_path: PathBuf,
    ffmpeg_path: Option<PathBuf>,
}

/// 从 URL 中提取平台名称
fn extract_platform_from_url(url: &str) -> Option<String> {
    let url_lower = url.to_lowercase();
    
    if url_lower.contains("bilibili.com") || url_lower.contains("b23.tv") {
        Some("bilibili".to_string())
    } else if url_lower.contains("youtube.com") || url_lower.contains("youtu.be") {
        Some("youtube".to_string())
    } else if url_lower.contains("twitter.com") || url_lower.contains("x.com") {
        Some("twitter".to_string())
    } else if url_lower.contains("instagram.com") {
        Some("instagram".to_string())
    } else if url_lower.contains("tiktok.com") {
        Some("tiktok".to_string())
    } else if url_lower.contains("douyin.com") {
        Some("douyin".to_string())
    } else if url_lower.contains("weibo.com") {
        Some("weibo".to_string())
    } else if url_lower.contains("xiaohongshu.com") || url_lower.contains("xhs.link") {
        Some("xiaohongshu".to_string())
    } else {
        None
    }
}

/// 从 Bilibili 空间 URL 中提取 UID
fn extract_bilibili_uid(url: &str) -> Option<String> {
    // URL 格式: https://space.bilibili.com/282357985 或 https://space.bilibili.com/282357985?xxx
    let url_lower = url.to_lowercase();
    if !url_lower.contains("space.bilibili.com") {
        return None;
    }
    
    // 提取数字 UID
    let parts: Vec<&str> = url.split("space.bilibili.com/").collect();
    if parts.len() < 2 {
        return None;
    }
    
    // 取 UID 部分，去掉查询参数
    let uid_part = parts[1].split('?').next()?;
    let uid_part = uid_part.split('/').next()?;
    
    // 验证是否为数字
    if uid_part.chars().all(|c| c.is_ascii_digit()) && !uid_part.is_empty() {
        Some(uid_part.to_string())
    } else {
        None
    }
}

/// 为指定平台创建临时 Cookie 文件
fn create_cookie_file(platform: &str, cookies: &[PlatformCookie]) -> Option<tempfile::NamedTempFile> {
    // 查找匹配平台且启用的 Cookie
    let platform_lower = platform.to_lowercase();
    let matching_cookie = cookies.iter().find(|c| {
        c.enabled && c.platform.to_lowercase() == platform_lower
    })?;
    
    // 创建临时文件
    let mut temp_file = tempfile::Builder::new()
        .prefix("magekit_cookies_")
        .suffix(".txt")
        .tempfile()
        .ok()?;
    
    // 写入 Netscape cookie 格式头
    writeln!(temp_file, "# Netscape HTTP Cookie File").ok()?;
    writeln!(temp_file, "# Generated by MageKit").ok()?;
    writeln!(temp_file).ok()?;
    
    // 解析并写入 Cookie
    // Cookie 字符串格式通常是: name1=value1; name2=value2; ...
    let domain = match platform_lower.as_str() {
        "bilibili" => ".bilibili.com",
        "youtube" => ".youtube.com",
        "twitter" => ".twitter.com",
        "instagram" => ".instagram.com",
        "tiktok" => ".tiktok.com",
        "douyin" => ".douyin.com",
        "weibo" => ".weibo.com",
        "xiaohongshu" => ".xiaohongshu.com",
        _ => return None,
    };
    
    // 解析 cookie 字符串
    for cookie_part in matching_cookie.cookie.split(';') {
        let cookie_part = cookie_part.trim();
        if cookie_part.is_empty() {
            continue;
        }
        
        // 分割 name=value
        if let Some((name, value)) = cookie_part.split_once('=') {
            let name = name.trim();
            let value = value.trim();
            
            // Netscape 格式: domain\tTRUE\tpath\tTRUE/FALSE\texpires\tname\tvalue
            // domain: cookie 域名
            // TRUE: 是否包含子域名 (以.开头的域名为TRUE)
            // path: cookie 路径
            // TRUE/FALSE: 是否仅 HTTPS (这里默认 FALSE)
            // expires: 过期时间 (0 表示会话 cookie，这里设置一个很大的值)
            // name: cookie 名称
            // value: cookie 值
            let expires = 2147483647u64; // 2038年
            writeln!(
                temp_file,
                "{}\tTRUE\t/\tFALSE\t{}\t{}\t{}",
                domain, expires, name, value
            ).ok()?;
        }
    }
    
    // 确保写入磁盘
    temp_file.flush().ok()?;
    
    tracing::info!("🍪 已为平台 {} 创建临时 Cookie 文件: {:?}", platform, temp_file.path());
    
    Some(temp_file)
}

impl VideoDownloader {
    /// 创建新的视频下载器
    pub fn new(yt_dlp_path: PathBuf, ffmpeg_path: Option<PathBuf>) -> Self {
        Self {
            yt_dlp_path,
            ffmpeg_path,
        }
    }

    /// 获取视频信息
    /// 
    /// # 参数
    /// - `url`: 视频 URL
    /// - `cookies`: 可选的平台 Cookie 列表，用于访问需要登录的内容
    pub async fn get_video_info(&self, url: &str, cookies: Option<&[PlatformCookie]>) -> DownloadResult<VideoInfo> {
        tracing::info!("🔍 获取视频信息，URL: {}", url);

        // 创建临时 Cookie 文件（如果有匹配的 Cookie）
        let cookie_file = if let Some(cookies) = cookies {
            if let Some(platform) = extract_platform_from_url(url) {
                create_cookie_file(&platform, cookies)
            } else {
                None
            }
        } else {
            None
        };

        let mut cmd = Command::new(&self.yt_dlp_path);
        cmd.arg("--dump-json")
            .arg("--no-download");
        
        // 添加 Cookie 参数
        if let Some(ref cookie_file) = cookie_file {
            tracing::info!("🍪 使用 Cookie 文件: {:?}", cookie_file.path());
            cmd.arg("--cookies").arg(cookie_file.path());
        }
        
        cmd.arg(url);

        let output = cmd.output()
            .await
            .map_err(|e| DownloadError::internal(format!("yt-dlp --dump-json failed: {}", e)))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            tracing::error!("❌ yt-dlp 获取视频信息失败: {}", stderr);
            return Err(DownloadError::extraction_failed(url, stderr.to_string()));
        }

        let json_str = String::from_utf8_lossy(&output.stdout);
        tracing::debug!("📄 yt-dlp 返回 JSON 长度: {} 字节", json_str.len());

        let video_data: VideoInfoData = serde_json::from_str(&json_str).map_err(|e| {
            tracing::error!("❌ JSON 解析失败: {}", e);
            DownloadError::extraction_failed(url, format!("Failed to parse JSON: {}", e))
        })?;

        tracing::info!(
            "✅ 视频信息获取成功: {} - {}",
            video_data.id,
            video_data.title
        );
        tracing::debug!(
            "📊 格式数量: {}, 时长: {:?}秒",
            video_data.formats.len(),
            video_data.duration
        );

        // 打印所有格式的详细信息用于调试
        for (i, fmt) in video_data.formats.iter().enumerate() {
            tracing::info!(
                "  格式[{}]: id={}, ext={:?}, res={:?}, vcodec={:?}, acodec={:?}",
                i,
                fmt.format_id,
                fmt.ext,
                fmt.resolution,
                fmt.vcodec,
                fmt.acodec
            );
        }

        Ok(video_data.into())
    }

    /// 获取 Bilibili UP 主空间的视频列表
    /// 
    /// 使用 Bilibili API 直接获取，比 yt-dlp 更快且能获取完整信息
    async fn get_bilibili_space_videos(&self, uid: &str, cookies: Option<&[PlatformCookie]>) -> DownloadResult<ChannelInfo> {
        tracing::info!("🔷 使用 Bilibili API 获取 UP 主视频列表");
        tracing::info!("   UID: {}", uid);
        
        // 构建请求 Cookie
        let cookie_header = if let Some(cookies) = cookies {
            cookies.iter()
                .find(|c| c.enabled && c.platform.to_lowercase() == "bilibili")
                .map(|c| c.cookie.clone())
        } else {
            None
        };
        
        // 获取 UP 主信息
        let user_info_url = format!("https://api.bilibili.com/x/space/wbi/acc/info?mid={}", uid);
        
        let client = reqwest::Client::new();
        let mut request = client.get(&user_info_url)
            .header("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36")
            .header("Referer", format!("https://space.bilibili.com/{}", uid));
        
        if let Some(ref cookie) = cookie_header {
            request = request.header("Cookie", cookie);
        }
        
        let user_response = request.send().await
            .map_err(|e| DownloadError::internal(format!("Failed to fetch user info: {}", e)))?;
        
        let user_json: serde_json::Value = user_response.json().await
            .map_err(|e| DownloadError::internal(format!("Failed to parse user info: {}", e)))?;
        
        let uploader_name = user_json["data"]["name"].as_str().unwrap_or("未知UP主").to_string();
        let uploader_face = user_json["data"]["face"].as_str().map(|s| s.to_string());
        
        tracing::info!("   UP 主: {}", uploader_name);
        
        // 获取视频列表（分页获取，每页最多 30 个）
        let mut entries = Vec::new();
        let mut page = 1;
        let page_size = 30;
        
        loop {
            let videos_url = format!(
                "https://api.bilibili.com/x/space/wbi/arc/search?mid={}&ps={}&pn={}&order=pubdate",
                uid, page_size, page
            );
            
            let mut request = client.get(&videos_url)
                .header("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36")
                .header("Referer", format!("https://space.bilibili.com/{}", uid));
            
            if let Some(ref cookie) = cookie_header {
                request = request.header("Cookie", cookie);
            }
            
            let videos_response = request.send().await
                .map_err(|e| DownloadError::internal(format!("Failed to fetch videos page {}: {}", page, e)))?;
            
            let videos_json: serde_json::Value = videos_response.json().await
                .map_err(|e| DownloadError::internal(format!("Failed to parse videos page {}: {}", page, e)))?;
            
            // 检查 API 返回状态
            let code = videos_json["code"].as_i64().unwrap_or(-1);
            if code != 0 {
                let message = videos_json["message"].as_str().unwrap_or("Unknown error");
                tracing::warn!("   Bilibili API 返回错误: code={}, message={}", code, message);
                break;
            }
            
            let vlist = &videos_json["data"]["list"]["vlist"];
            if !vlist.is_array() {
                break;
            }
            
            let video_array = vlist.as_array().unwrap();
            if video_array.is_empty() {
                break;
            }
            
            tracing::info!("   第 {} 页: {} 个视频", page, video_array.len());
            
            for video in video_array {
                let bvid = video["bvid"].as_str().unwrap_or("").to_string();
                let title = video["title"].as_str().unwrap_or(&bvid).to_string();
                let pic = video["pic"].as_str().map(|s| {
                    // Bilibili 图片可能需要添加 https: 前缀
                    if s.starts_with("//") {
                        format!("https:{}", s)
                    } else {
                        s.to_string()
                    }
                });
                let duration = video["length"].as_str().and_then(|s| {
                    // 格式: "mm:ss" 或 "hh:mm:ss"
                    let parts: Vec<&str> = s.split(':').collect();
                    match parts.len() {
                        2 => {
                            let mins: u64 = parts[0].parse().ok()?;
                            let secs: u64 = parts[1].parse().ok()?;
                            Some(mins * 60 + secs)
                        }
                        3 => {
                            let hours: u64 = parts[0].parse().ok()?;
                            let mins: u64 = parts[1].parse().ok()?;
                            let secs: u64 = parts[2].parse().ok()?;
                            Some(hours * 3600 + mins * 60 + secs)
                        }
                        _ => None,
                    }
                });
                
                if !bvid.is_empty() {
                    entries.push(ChannelVideoEntry {
                        id: bvid.clone(),
                        title,
                        url: format!("https://www.bilibili.com/video/{}", bvid),
                        duration,
                        thumbnail: pic,
                        uploader: Some(uploader_name.clone()),
                        playlist_index: Some(entries.len() as u32 + 1),
                        selected: false,
                    });
                }
            }
            
            // 检查是否还有更多页
            let total = videos_json["data"]["page"]["count"].as_i64().unwrap_or(0) as usize;
            if entries.len() >= total || video_array.len() < page_size {
                break;
            }
            
            page += 1;
            
            // 添加小延迟避免请求过快
            tokio::time::sleep(Duration::from_millis(100)).await;
        }
        
        tracing::info!("✅ Bilibili 空间视频获取成功: {} - 共 {} 个视频", uploader_name, entries.len());
        
        // 打印前 5 个视频的详细信息
        for (i, entry) in entries.iter().take(5).enumerate() {
            tracing::info!(
                "📹 视频[{}]: id={}, title={}, thumbnail={:?}, duration={:?}",
                i + 1,
                entry.id,
                entry.title,
                entry.thumbnail.as_ref().map(|t| if t.len() > 50 { &t[..50] } else { t }),
                entry.duration
            );
        }
        if entries.len() > 5 {
            tracing::info!("   ... 还有 {} 个视频", entries.len() - 5);
        }
        
        Ok(ChannelInfo {
            id: uid.to_string(),
            title: uploader_name.clone(),
            url: format!("https://space.bilibili.com/{}", uid),
            uploader: Some(uploader_name),
            description: None,
            video_count: entries.len(),
            thumbnail: uploader_face,
            entries,
        })
    }

    /// 获取频道/播放列表的所有视频信息
    ///
    /// 使用 `--flat-playlist` 参数快速获取视频列表（仅元数据，不下载）
    /// 支持的 URL 类型：
    /// - YouTube 频道: @username, /user/, /channel/, /c/
    /// - YouTube 播放列表: /playlist?list=
    /// - Bilibili UP主空间: space.bilibili.com/uid
    /// 
    /// # 参数
    /// - `url`: 频道或播放列表的 URL
    /// - `cookies`: 可选的平台 Cookie 列表，用于访问需要登录的内容
    pub async fn get_channel_videos(&self, url: &str, cookies: Option<&[PlatformCookie]>) -> DownloadResult<ChannelInfo> {
        tracing::info!("📺 获取频道/播放列表信息");
        tracing::info!("   URL: {}", url);
        
        // 检测是否是 Bilibili 空间链接
        // 注意: Bilibili API 需要 wbi 签名，比较复杂，暂时使用 yt-dlp
        // TODO: 未来可以实现完整的 Bilibili API 支持获取更多信息
        if url.contains("space.bilibili.com") {
            tracing::info!("   检测到 Bilibili 空间，使用 yt-dlp 获取列表");
        }
        
        tracing::info!("   yt-dlp路径: {:?}", self.yt_dlp_path);
        
        // 创建临时 Cookie 文件（如果有匹配的 Cookie）
        let cookie_file = if let Some(cookies) = cookies {
            if let Some(platform) = extract_platform_from_url(url) {
                create_cookie_file(&platform, cookies)
            } else {
                None
            }
        } else {
            None
        };
        
        let mut cmd = Command::new(&self.yt_dlp_path);
        // 使用 --flat-playlist 快速获取视频列表，但不获取每个视频的详细信息
        // 对于 Bilibili 和 YouTube，基本的 id/url 就足够用于下载
        // title 会在下载时自动获取
        cmd.arg("--flat-playlist") // 快速获取列表
            .arg("--dump-single-json") // 输出单个 JSON 对象
            .arg("--no-warnings") // 减少警告输出
            // 请求 Bilibili 提取器返回更多信息
            .arg("--extractor-args")
            .arg("BiliBiliSpace:metadata=true")
            .arg("-v"); // 详细输出
        
        // 添加 Cookie 参数
        if let Some(ref cookie_file) = cookie_file {
            tracing::info!("   使用 Cookie 文件: {:?}", cookie_file.path());
            cmd.arg("--cookies").arg(cookie_file.path());
        }
        
        cmd.arg(url);
        
        tracing::info!("   执行命令: {:?}", cmd);

        let output = cmd.output()
            .await
            .map_err(|e| {
                tracing::error!("❌ 执行 yt-dlp 失败: {}", e);
                DownloadError::internal(format!("yt-dlp --flat-playlist failed: {}", e))
            })?;

        tracing::info!("   退出码: {:?}", output.status.code());
        
        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            let stdout = String::from_utf8_lossy(&output.stdout);
            tracing::error!("❌ yt-dlp 获取频道信息失败");
            tracing::error!("   stderr: {}", stderr);
            tracing::error!("   stdout长度: {} 字节", stdout.len());
            if !stdout.is_empty() {
                tracing::debug!("   stdout前500字符: {}", &stdout.chars().take(500).collect::<String>());
            }
            return Err(DownloadError::extraction_failed(url, stderr.to_string()));
        }

        let json_str = String::from_utf8_lossy(&output.stdout);
        tracing::info!("✅ yt-dlp 返回数据长度: {} 字节", json_str.len());

        // --dump-single-json 输出一个 JSON 对象（可能跨多行）
        // 打印前 1000 字符用于调试
        let preview = if json_str.len() > 1000 { &json_str[..1000] } else { &json_str };
        tracing::info!("📋 原始 JSON 输出预览: {}", preview);

        if json_str.is_empty() {
            return Err(DownloadError::extraction_failed(
                url,
                "No data returned from yt-dlp".to_string(),
            ));
        }

        // 解析频道/播放列表信息 (--dump-single-json 返回单个 JSON 对象)
        let channel_data: ChannelInfoData = serde_json::from_str(&json_str).map_err(|e| {
            tracing::error!("❌ JSON 解析失败: {}", e);
            DownloadError::extraction_failed(url, format!("Failed to parse channel JSON: {}", e))
        })?;

        // 解析视频条目
        let mut entries: Vec<ChannelVideoEntry> = Vec::new();

        // 从 channel_data 的 entries 中获取视频信息
        if let Some(ref data_entries) = channel_data.entries {
            tracing::info!("📋 解析 {} 个视频条目", data_entries.len());
            for (i, entry) in data_entries.iter().enumerate() {
                // 打印前 3 个条目的原始 JSON 用于调试
                if i < 3 {
                    tracing::info!("   原始条目[{}]: {}", i + 1, 
                        serde_json::to_string(entry).unwrap_or_else(|_| "无法序列化".to_string()));
                }
                if let Some(video_entry) = parse_channel_entry(entry) {
                    entries.push(video_entry);
                }
            }
        }

        // 如果没有从 entries 中获取到，尝试按行解析（兼容旧格式）
        if entries.is_empty() {
            let lines: Vec<&str> = json_str.lines().collect();
            if lines.len() > 1 {
                tracing::info!("📋 尝试按行解析 {} 行", lines.len());
                for (index, line) in lines.iter().skip(1).enumerate() {
                    if let Ok(entry_data) = serde_json::from_str::<ChannelEntryData>(line) {
                        let entry = ChannelVideoEntry {
                            id: entry_data.id.clone(),
                            title: entry_data.title.unwrap_or_else(|| entry_data.id.clone()),
                            url: entry_data
                                .url
                                .or(entry_data.webpage_url)
                                .unwrap_or_else(|| {
                                    format!("https://www.youtube.com/watch?v={}", entry_data.id)
                                }),
                            duration: entry_data.duration.map(|d| d as u64),
                            thumbnail: entry_data.thumbnail,
                            uploader: entry_data.uploader,
                            playlist_index: Some(index as u32 + 1),
                            selected: false,
                        };
                        entries.push(entry);
                    }
                }
            }
        }

        let video_count = entries.len();
        tracing::info!(
            "✅ 频道信息获取成功: {} - 共 {} 个视频",
            channel_data.title.as_deref().unwrap_or("未知频道"),
            video_count
        );
        
        // 打印每个视频的详细信息用于调试
        for (i, entry) in entries.iter().take(5).enumerate() {
            tracing::info!(
                "📹 视频[{}]: id={}, title={}, url={}, thumbnail={:?}, duration={:?}",
                i + 1,
                entry.id,
                entry.title,
                entry.url,
                entry.thumbnail,
                entry.duration
            );
        }
        if entries.len() > 5 {
            tracing::info!("   ... 还有 {} 个视频", entries.len() - 5);
        }

        Ok(ChannelInfo {
            id: channel_data.id.unwrap_or_else(|| "unknown".to_string()),
            title: channel_data.title.unwrap_or_else(|| "未知频道".to_string()),
            url: url.to_string(),
            uploader: channel_data.uploader.or(channel_data.channel),
            description: channel_data.description,
            video_count,
            thumbnail: channel_data.thumbnail,
            entries,
        })
    }

    /// 开始下载视频
    /// 
    /// # 参数
    /// - `task_id`: 任务 ID
    /// - `url`: 视频 URL
    /// - `options`: 下载选项
    /// - `progress_tx`: 进度通知发送器
    /// - `cookies`: 可选的平台 Cookie 列表，用于访问需要登录的内容
    pub async fn start_download(
        &self,
        task_id: TaskId,
        url: &str,
        options: DownloadOptions,
        progress_tx: mpsc::Sender<DownloadProgress>,
        cookies: Option<&[PlatformCookie]>,
    ) -> DownloadResult<PathBuf> {
        tracing::info!("📥 开始下载任务 {}", task_id);
        tracing::info!("  URL: {}", url);
        tracing::info!("  输出目录: {:?}", options.output_path);
        tracing::info!("  格式: {}", options.format_id);
        
        // 创建临时 Cookie 文件（如果有匹配的 Cookie）
        let cookie_file = if let Some(cookies) = cookies {
            if let Some(platform) = extract_platform_from_url(url) {
                create_cookie_file(&platform, cookies)
            } else {
                None
            }
        } else {
            None
        };

        let mut cmd = Command::new(&self.yt_dlp_path);

        // 基本参数
        let output_template = options.output_path.join(
            options
                .output_template
                .as_deref()
                .unwrap_or("%(title)s.%(ext)s"),
        );

        // 添加 Cookie 参数（如果有）
        if let Some(ref cookie_file) = cookie_file {
            tracing::info!("🍪 使用 Cookie 文件: {:?}", cookie_file.path());
            cmd.arg("--cookies").arg(cookie_file.path());
        }

        cmd.arg(url)
            .arg("--format")
            .arg(&options.format_id)
            .arg("--output")
            .arg(output_template.to_string_lossy().as_ref())
            // 添加进度相关参数
            .arg("--newline") // 确保每行进度都输出
            .arg("--progress") // 显示进度条
            .arg("--print")
            .arg("after_move:filepath"); // 最终文件路径输出到 stdout

        tracing::debug!("  输出模板: {:?}", output_template);

        // 元数据选项
        if options.embed_metadata {
            cmd.arg("--embed-metadata");
        }
        if options.embed_thumbnail {
            cmd.arg("--embed-thumbnail");
        }

        // 音频提取选项
        if options.extract_audio {
            cmd.arg("--extract-audio");
            if let Some(audio_format) = &options.audio_format {
                cmd.arg("--audio-format").arg(audio_format);
            }
        }

        // 字幕选项
        for lang in &options.subtitle_langs {
            cmd.arg("--sub-langs").arg(lang);
        }
        if options.embed_subs {
            cmd.arg("--embed-subs");
        }
        if options.write_subs {
            cmd.arg("--write-subs");
        }
        if options.write_auto_subs {
            cmd.arg("--write-auto-subs");
        }

        // 使用FFmpeg进行后处理
        if let Some(ffmpeg_path) = &self.ffmpeg_path {
            cmd.env("FFMPEG", ffmpeg_path);
        }

        // 创建子进程
        let mut child = cmd
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .map_err(|e| DownloadError::internal(format!("yt-dlp download failed: {}", e)))?;

        // 发送开始事件
        let _ = progress_tx
            .send(DownloadProgress::Started {
                task_id,
                url: url.to_string(),
            })
            .await;

        // 监控下载进度
        let output_path = self
            .monitor_download_progress(task_id, &mut child, &progress_tx)
            .await?;

        tracing::info!("Download completed for task {}: {:?}", task_id, output_path);
        Ok(output_path)
    }

    /// 监控下载进度
    async fn monitor_download_progress(
        &self,
        task_id: TaskId,
        child: &mut Child,
        progress_tx: &mpsc::Sender<DownloadProgress>,
    ) -> DownloadResult<PathBuf> {
        use tokio::io::{AsyncBufReadExt, BufReader};

        // 同时读取 stdout 和 stderr
        let stdout = child
            .stdout
            .take()
            .ok_or_else(|| DownloadError::internal("Failed to capture stdout".to_string()))?;
        let stderr = child
            .stderr
            .take()
            .ok_or_else(|| DownloadError::internal("Failed to capture stderr".to_string()))?;

        let mut stdout_reader = BufReader::new(stdout);
        let mut stderr_reader = BufReader::new(stderr);

        let mut stdout_line = String::new();
        let mut stderr_line = String::new();

        let mut output_path: Option<PathBuf> = None;
        let mut final_path_from_print: Option<PathBuf> = None;

        // 使用 select 同时读取两个流
        loop {
            tokio::select! {
                result = stdout_reader.read_line(&mut stdout_line) => {
                    match result {
                        Ok(0) => {}, // stdout EOF
                        Ok(_) => {
                            let trimmed = stdout_line.trim();
                            if !trimmed.is_empty() {
                                tracing::debug!("[yt-dlp stdout] {}", trimmed);

                                // --print after_move:filepath 的输出会在 stdout
                                // 这通常是最终的文件路径
                                if !trimmed.starts_with('[') && !trimmed.contains('%') {
                                    let potential_path = PathBuf::from(trimmed);
                                    // 检查是否像文件路径
                                    if trimmed.contains('/') || trimmed.contains('.') {
                                        tracing::info!("📁 从 stdout 检测到文件路径: {:?}", potential_path);
                                        final_path_from_print = Some(potential_path);
                                    }
                                }
                            }
                            stdout_line.clear();
                        }
                        Err(e) => {
                            tracing::warn!("Error reading stdout: {}", e);
                        }
                    }
                }
                result = stderr_reader.read_line(&mut stderr_line) => {
                    match result {
                        Ok(0) => break, // stderr EOF, 进程可能结束
                        Ok(_) => {
                            let trimmed = stderr_line.trim();
                            if !trimmed.is_empty() {
                                tracing::debug!("[yt-dlp stderr] {}", trimmed);
                            }

                            // 解析下载进度信息
                            if let Some(progress) = self.parse_progress_line(&stderr_line) {
                                let _ = progress_tx.send(DownloadProgress::Progress {
                                    task_id,
                                    percent: progress.percent,
                                    speed: progress.speed,
                                    eta: progress.eta,
                                }).await;
                            }

                            // 解析输出文件路径 - 支持多种格式
                            if let Some(path) = self.extract_output_path(&stderr_line) {
                                tracing::info!("📁 从 stderr 检测到输出文件: {:?}", path);
                                output_path = Some(path);
                            }

                            stderr_line.clear();
                        }
                        Err(e) => {
                            tracing::warn!("Error reading stderr: {}", e);
                        }
                    }
                }
            }
        }

        // 等待进程完成
        let status = child
            .wait()
            .await
            .map_err(|e| DownloadError::internal(format!("wait for yt-dlp failed: {}", e)))?;

        if !status.success() {
            tracing::error!("❌ yt-dlp 进程退出码: {:?}", status.code());
            return Err(DownloadError::download_failed(
                "unknown",
                format!("Process exited with code: {:?}", status.code()),
            ));
        }

        // 优先使用 --print 输出的路径，否则使用从 stderr 检测到的路径
        let final_path = final_path_from_print.or(output_path);

        match &final_path {
            Some(path) => tracing::info!("✅ 下载完成，输出文件: {:?}", path),
            None => tracing::warn!("⚠️ 下载完成但未检测到输出文件路径"),
        }

        final_path.ok_or_else(|| DownloadError::internal("无法确定输出文件路径".to_string()))
    }

    /// 解析进度行
    fn parse_progress_line(&self, line: &str) -> Option<ProgressInfo> {
        // yt-dlp 进度格式示例:
        // [download]   5.2% of 125.45MiB at 512.34KiB/s ETA 02:15
        if !line.contains("[download]") {
            return None;
        }

        let parts: Vec<&str> = line.split_whitespace().collect();
        if parts.len() < 8 {
            return None;
        }

        let percent_str = parts[1].trim_end_matches('%');
        let percent = percent_str.parse::<f64>().ok()? as f32;

        let speed = if parts[6] == "at" && parts.len() > 7 {
            self.parse_speed(parts[7])
        } else {
            None
        };

        let eta = if parts.len() > 8 && parts[8] == "ETA" && parts.len() > 9 {
            self.parse_eta(parts[9])
        } else {
            None
        };

        Some(ProgressInfo {
            percent,
            speed,
            eta,
        })
    }

    /// 解析速度 (如 512.34KiB/s)
    fn parse_speed(&self, speed_str: &str) -> Option<u64> {
        let speed_str = speed_str.trim_end_matches("/s");
        let (num_str, unit) = speed_str.split_at(speed_str.len().saturating_sub(2));

        let num: f64 = num_str.parse().ok()?;
        let multiplier = match unit {
            "B" => 1.0,
            "KB" | "KiB" => 1024.0,
            "MB" | "MiB" => 1024.0 * 1024.0,
            "GB" | "GiB" => 1024.0 * 1024.0 * 1024.0,
            _ => return None,
        };

        Some((num * multiplier) as u64)
    }

    /// 解析ETA (如 02:15)
    fn parse_eta(&self, eta_str: &str) -> Option<Duration> {
        let parts: Vec<&str> = eta_str.split(':').collect();
        if parts.len() != 2 {
            return None;
        }

        let minutes: u64 = parts[0].parse().ok()?;
        let seconds: u64 = parts[1].parse().ok()?;

        Some(Duration::from_secs(minutes * 60 + seconds))
    }

    /// 从yt-dlp输出中提取文件路径
    fn extract_output_path(&self, line: &str) -> Option<PathBuf> {
        // 支持多种 yt-dlp 输出格式:
        // [download] Destination: /path/to/file.mp4
        // [Merger] Merging formats into "/path/to/file.mp4"
        // [ExtractAudio] Destination: /path/to/file.mp3
        // [download] /path/to/file.mp4 has already been downloaded
        // [ffmpeg] Merging formats into "/path/to/file.webm"

        if let Some(start) = line.find("Destination:") {
            let path_part = &line[start + 12..]; // "Destination:" 的长度
            return Some(PathBuf::from(path_part.trim()));
        }

        // 处理 [Merger] Merging formats into "path" 格式
        if line.contains("Merging formats into") {
            if let Some(start) = line.find('"') {
                if let Some(end) = line.rfind('"') {
                    if end > start {
                        let path_str = &line[start + 1..end];
                        return Some(PathBuf::from(path_str));
                    }
                }
            }
        }

        // 处理 "has already been downloaded" 格式
        if line.contains("has already been downloaded") {
            // [download] /path/to/file.mp4 has already been downloaded
            if let Some(start) = line.find("[download]") {
                let rest = &line[start + 10..].trim();
                if let Some(end) = rest.find(" has already been downloaded") {
                    return Some(PathBuf::from(&rest[..end]));
                }
            }
        }

        None
    }
}

/// 下载进度信息
#[derive(Debug)]
struct ProgressInfo {
    percent: f32,
    speed: Option<u64>,
    eta: Option<Duration>,
}

/// 下载进度事件
#[derive(Debug, Clone)]
pub enum DownloadProgress {
    Started {
        task_id: TaskId,
        url: String,
    },
    Progress {
        task_id: TaskId,
        percent: f32,
        speed: Option<u64>,
        eta: Option<Duration>,
    },
    Completed {
        task_id: TaskId,
        output_path: PathBuf,
    },
    Error {
        task_id: TaskId,
        error: String,
    },
}

/// yt-dlp JSON输出的数据结构
#[derive(Debug, Deserialize)]
struct VideoInfoData {
    id: String,
    title: String,
    description: Option<String>,
    duration: Option<f64>,
    uploader: Option<String>,
    upload_date: Option<String>,
    thumbnail: Option<String>,
    #[serde(default)]
    formats: Vec<FormatData>,
    webpage_url: String,
}

/// 频道/播放列表的 JSON 数据结构
#[derive(Debug, Deserialize)]
struct ChannelInfoData {
    id: Option<String>,
    title: Option<String>,
    description: Option<String>,
    uploader: Option<String>,
    channel: Option<String>,
    thumbnail: Option<String>,
    #[serde(default)]
    entries: Option<Vec<serde_json::Value>>,
}

/// 频道中视频条目的 JSON 数据结构
#[derive(Debug, Deserialize)]
struct ChannelEntryData {
    id: String,
    title: Option<String>,
    url: Option<String>,
    webpage_url: Option<String>,
    duration: Option<f64>,
    thumbnail: Option<String>,
    uploader: Option<String>,
}

/// 解析频道条目
fn parse_channel_entry(value: &serde_json::Value) -> Option<ChannelVideoEntry> {
    let entry: ChannelEntryData = serde_json::from_value(value.clone()).ok()?;

    // 如果没有 title，使用 "视频 {id}" 格式
    let title = entry.title.unwrap_or_else(|| {
        if entry.id.starts_with("BV") {
            format!("视频 {}", entry.id)
        } else {
            entry.id.clone()
        }
    });
    
    // 为 Bilibili 视频生成默认缩略图 URL
    let thumbnail = entry.thumbnail.or_else(|| {
        if entry.id.starts_with("BV") {
            // Bilibili 缩略图格式: https://i0.hdslb.com/bfs/archive/{aid}.jpg
            // 由于我们只有 BV 号，暂时不生成缩略图
            None
        } else {
            None
        }
    });

    Some(ChannelVideoEntry {
        id: entry.id.clone(),
        title,
        url: entry
            .url
            .or(entry.webpage_url)
            .unwrap_or_else(|| format!("https://www.youtube.com/watch?v={}", entry.id)),
        duration: entry.duration.map(|d| d as u64),
        thumbnail,
        uploader: entry.uploader,
        playlist_index: None,
        selected: false,
    })
}

#[derive(Debug, Deserialize)]
struct FormatData {
    format_id: String,
    ext: Option<String>,
    resolution: Option<String>,
    fps: Option<f32>,
    filesize: Option<u64>,
    vcodec: Option<String>,
    acodec: Option<String>,
    #[serde(default, deserialize_with = "deserialize_quality")]
    quality: Option<String>,
}

/// 自定义反序列化器，处理 quality 字段可能是数字或字符串的情况
fn deserialize_quality<'de, D>(deserializer: D) -> Result<Option<String>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    use serde::de::{self, Visitor};

    struct QualityVisitor;

    impl<'de> Visitor<'de> for QualityVisitor {
        type Value = Option<String>;

        fn expecting(&self, formatter: &mut std::fmt::Formatter) -> std::fmt::Result {
            formatter.write_str("a string, number, or null")
        }

        fn visit_none<E>(self) -> Result<Self::Value, E>
        where
            E: de::Error,
        {
            Ok(None)
        }

        fn visit_unit<E>(self) -> Result<Self::Value, E>
        where
            E: de::Error,
        {
            Ok(None)
        }

        fn visit_some<D>(self, deserializer: D) -> Result<Self::Value, D::Error>
        where
            D: serde::Deserializer<'de>,
        {
            deserializer.deserialize_any(QualityVisitor)
        }

        fn visit_str<E>(self, value: &str) -> Result<Self::Value, E>
        where
            E: de::Error,
        {
            Ok(Some(value.to_string()))
        }

        fn visit_string<E>(self, value: String) -> Result<Self::Value, E>
        where
            E: de::Error,
        {
            Ok(Some(value))
        }

        fn visit_i64<E>(self, value: i64) -> Result<Self::Value, E>
        where
            E: de::Error,
        {
            Ok(Some(value.to_string()))
        }

        fn visit_u64<E>(self, value: u64) -> Result<Self::Value, E>
        where
            E: de::Error,
        {
            Ok(Some(value.to_string()))
        }

        fn visit_f64<E>(self, value: f64) -> Result<Self::Value, E>
        where
            E: de::Error,
        {
            Ok(Some(value.to_string()))
        }
    }

    deserializer.deserialize_option(QualityVisitor)
}

impl From<VideoInfoData> for VideoInfo {
    fn from(data: VideoInfoData) -> Self {
        Self {
            id: data.id,
            title: data.title,
            description: data.description,
            duration: data.duration.map(Duration::from_secs_f64),
            uploader: data.uploader,
            upload_date: data.upload_date,
            thumbnail: data.thumbnail,
            formats: data
                .formats
                .into_iter()
                .map(|f| VideoFormat {
                    format_id: f.format_id,
                    ext: f.ext.unwrap_or_else(|| "unknown".to_string()),
                    resolution: f.resolution,
                    fps: f.fps,
                    filesize: f.filesize,
                    vcodec: f.vcodec,
                    acodec: f.acodec,
                    quality: f.quality,
                })
                .collect(),
            url: data.webpage_url,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_progress_line() {
        let downloader = VideoDownloader::new(PathBuf::from("/usr/bin/yt-dlp"), None);

        let line = "[download]   45.2% of 125.45MiB at 1.2MiB/s ETA 01:23";
        let progress = downloader.parse_progress_line(line);

        assert!(progress.is_some());
        let progress = progress.unwrap();
        assert!((progress.percent - 45.2).abs() < 0.01);
        assert!(progress.speed.is_some());
        assert!(progress.eta.is_some());
    }

    #[test]
    fn test_extract_output_path() {
        let downloader = VideoDownloader::new(PathBuf::from("/usr/bin/yt-dlp"), None);

        let line = "[download] Destination: /path/to/video.mp4";
        let path = downloader.extract_output_path(line);

        assert!(path.is_some());
        assert_eq!(path.unwrap(), PathBuf::from("/path/to/video.mp4"));
    }
}
