#!/usr/bin/env python3
"""Validate locale coverage and generate the dependency-free Rust catalog.

Run with --write after editing locales/en.json or locales/zh.json. Without it,
this command checks the checked-in generated catalog, translation parity and
format arguments. Placeholder text used in a path example is not an argument.
"""
import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent
PLACEHOLDER = re.compile(r"(?<!\{)\{(?:[A-Za-z_][A-Za-z_0-9]*|\d*)?(?::[^{}]*)?\}(?!\})")


def rust_string(value):
    return json.dumps(value, ensure_ascii=False).replace('\\u2028', '\u2028').replace('\\u2029', '\u2029')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    catalogs = {locale: json.loads((ROOT / 'locales' / f'{locale}.json').read_text()) for locale in ('en', 'zh')}
    assert catalogs['en'].keys() == catalogs['zh'].keys(), 'Locale keys differ'
    for key, english in catalogs['en'].items():
        assert english.strip(), f'Empty English translation: {key}'
        assert not re.search('[\u3400-\u9fff]', english), f'Untranslated English entry: {key}'
        if PLACEHOLDER.findall(catalogs['zh'][key]):
            assert PLACEHOLDER.findall(english) == PLACEHOLDER.findall(catalogs['zh'][key]), f'Placeholder mismatch: {key}'
    # Verify every explicit source call references an existing message. Functional
    # strings and user-authored content are deliberately outside this API.
    calls = re.compile(r'(?:crate::i18n::(?:tr|format|input)|Message::(?:plain|new))\s*\(\s*("(?:\\.|[^"\\])*")')
    for source in (ROOT / 'src').rglob('*.rs'):
        if 'i18n' in source.parts:
            continue
        for match in calls.finditer(source.read_text()):
            key = json.loads(match.group(1))
            assert key in catalogs['en'], f'Missing message in {source.relative_to(ROOT)}: {key}'
    generated = '// Generated by scripts/check_i18n.py --write. Edit the JSON catalogs instead.\n'
    # Rust binary_search uses Unicode scalar/UTF-8 lexical order, matching Python.
    for locale, catalog in catalogs.items():
        generated += f'#[rustfmt::skip]\npub(super) const {locale.upper()}: &[(&str, &str)] = &[\n'
        for key in sorted(catalog):
            generated += f'    ({rust_string(key)}, {rust_string(catalog[key])}),\n'
        generated += '];\n'
    target = ROOT / 'src' / 'i18n' / 'catalog.rs'
    if args.write:
        target.write_text(generated)
    else:
        assert target.read_text() == generated, 'Run scripts/check_i18n.py --write to update the Rust catalog'
    print(f'Validated {len(catalogs["en"])} bilingual messages and format placeholders')


if __name__ == '__main__':
    main()
